
version: '3.1'

services:

  postgresql:
    image: postgres:10
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: publisher
      POSTGRES_USER: msp_user
      POSTGRES_PASSWORD: msp_password