
version: '3.1'

services:

  postgresql:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: koa_app_db
      POSTGRES_USER: koa_app_user
      POSTGRES_PASSWORD: koa_app_pass